### ISSUE TITLE
Close Button Not Functioning Properly in Todo List Application

### ISSUE THREAD

**Issue by SandeepVashishtha** [muskanchoudhary001/my-ToDo-List#17]
pls assign this issue to me i'll fix it and fix the UI also

**Comment by muskanchoudhary001** [comment]
Hi @SandeepVashishtha ,

Make the changes and also do attach screenshots for the changes you have made with the PR request .

**Comment by SandeepVashishtha** [comment]
@muskanchoudhary001 now you can deploy this site using GitHub pages

**Comment by muskanchoudhary001** [comment]
for

**Comment by muskanchoudhary001** [comment]
If you are done should i close this issue!!
