### ISSUE TITLE
Store the to do list in localstorage

### ISSUE THREAD

**Issue by tanish35** [muskanchoudhary001/my-ToDo-List#20]
Upon refreshing the page the todo list gets deleted. The todo list should get stored in the browser so thatupon refreshing the user can get back the notes

Pls assign me this issue under hacktoberfest

**Comment by surajkus** [comment]
![Screenshot 2024-10-04 231918](https://github.com/user-attachments/assets/bc6d01d5-4065-4f68-8222-3b58b2f40d27)

This is the design i want to commit...

**Comment by muskanchoudhary001** [comment]
great work done!!
